#!/bin/sh

for i in $(ls)
do
	if test -f $i									# test command gives true or false output. -f to check wthether it's a file or not
	then
		if test -x $i								# -x - to check the file is executable or not
		then
			if [ ! -d executables ]					# -d - to check the directory is exists or not, ie help when runs the script agian.
			then
				mkdir ./executables
			fi	
			mv $i executables
		fi
	fi
done	
